global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        channel: '#alerts'
        username: 'Alertmanager'
        api_url: 'https://hooks.slack.com/services/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'
        text: "{{ .CommonAnnotations.summary }}"
